"""Golden-file parity tests for llm_router_utils.sglang.srt.mem_cache.utils.

Two layers of coverage:

1. test_hash_matches_sglang_golden
     Byte-level parity: this implementation's output == real sglang C++ output.
     Cases come from test/fixtures/hash_golden.json, generated by
     test/fixtures/gen_hash_golden.py on a real sglang host.  If the
     golden file is absent, the test skips (e.g. on a dev machine that
     hasn't run the generator).

2. Behavioral tests (no sglang required)
     Edge cases the golden file doesn't cover:
     - uint32 overflow raises (sglang's checked_u32 also raises)
     - compute_node_hash_values reads parent.hash_value[-1] as prior
     - split_node_hash_value boundary semantics
     - parent=None differs from parent=any real hash
     These run on every machine, no golden file needed.
"""

from __future__ import annotations

import json
import os
from typing import Any

import pytest

from llm_router_utils.sglang.srt.mem_cache.utils import (
    compute_node_hash_values,
    get_hash_str,
    hash_str_to_int64,
    split_node_hash_value,
)

# Golden file lives at test/fixtures/hash_golden.json; this test lives at
# test/unit/mem_cache/test_hash_golden.py — relative path is ../../fixtures/.
GOLDEN_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "..", "fixtures", "hash_golden.json",
)


def _load_golden() -> dict | None:
    if not os.path.exists(GOLDEN_PATH):
        return None
    with open(GOLDEN_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


_GOLDEN = _load_golden()


# ---------------------------------------------------------------------------
# Layer 1: byte-level parity against real sglang C++ output
# ---------------------------------------------------------------------------


def _golden_cases() -> list[dict]:
    if _GOLDEN is None:
        return []
    return [c for c in _GOLDEN["cases"] if c.get("error") is None]


golden_skip = pytest.mark.skipif(
    _GOLDEN is None,
    reason=(
        "test/fixtures/hash_golden.json not found.  Run "
        "test/fixtures/gen_hash_golden.py on a real sglang host and "
        "commit the output to enable this test."
    ),
)


@golden_skip
@pytest.mark.parametrize(
    "case", _golden_cases(), ids=[c["name"] for c in _golden_cases()]
)
def test_hash_matches_sglang_golden(case: dict[str, Any]):
    """get_hash_str must produce byte-identical output to sglang."""
    token_ids = case["token_ids"]
    parent_hash = case["parent_hash"]
    page_size = case["page_size"]
    expected_hash = case["hash"]
    expected_int64 = case["int64"]

    if page_size is None:
        actual = get_hash_str(token_ids, parent_hash)
    else:
        actual = get_hash_str(token_ids, parent_hash, page_size=page_size)

    assert actual == expected_hash, (
        f"hash mismatch for case {case['name']!r}:\n"
        f"  token_ids={token_ids[:8]}{'...' if len(token_ids) > 8 else ''}\n"
        f"  parent_hash={parent_hash!r}\n"
        f"  page_size={page_size}\n"
        f"  expected={expected_hash!r}\n"
        f"  actual=  {actual!r}"
    )

    if expected_int64 is not None:
        h = actual[0] if isinstance(actual, list) else actual
        actual_int64 = hash_str_to_int64(h)
        assert actual_int64 == expected_int64, (
            f"int64 mismatch for case {case['name']!r}: "
            f"expected={expected_int64}, actual={actual_int64}"
        )


@golden_skip
def test_golden_algorithm_metadata_matches_assumptions():
    """Sanity: catches algorithm drift before per-case tests confuse."""
    assert _GOLDEN is not None
    algo = _GOLDEN.get("algorithm", {})

    assert algo.get("hash_func") == "SHA256"
    assert algo.get("prior_digest_bytes") == 32
    assert "uint32" in algo.get("token_encoding", "")
    assert algo.get("output_hex_chars") == 64
    assert algo.get("int64_uses_first_hex_chars") == 16


# ---------------------------------------------------------------------------
# Layer 2: behavioral tests (no sglang, no golden file)
# ---------------------------------------------------------------------------


def test_token_id_over_uint32_raises():
    """sglang's checked_u32 throws for token ids > 2**32-1.

    llm_router_utils uses array.array("I") which raises OverflowError in the
    same case -- fail loud, not silently truncate.
    """
    with pytest.raises(OverflowError):
        get_hash_str([2**32])  # one past uint32 max


def test_parent_none_differs_from_any_parent():
    """Root block (prior=None) must differ from a block with any parent.

    sglang's hash_page: has_prior_digest=False skips SHA256_Update of
    prior_digest entirely.  kv_tree's root nodes have parent_hash=None.
    """
    no_parent = get_hash_str([1, 2, 3])
    some_parent = get_hash_str([100])
    with_parent = get_hash_str([1, 2, 3], some_parent)
    assert no_parent != with_parent


def test_paged_chain_propagates_parent():
    """In paged mode, page N's hash depends on page N-1's hash (chain).

    sglang's hash_pages_to_hex_blob: each page's digest becomes the next
    page's prior_digest.  Golden covers this via paged_with_parent, but
    this test runs without the golden file.
    """
    pages_a = get_hash_str([1, 2, 3, 4, 5, 6], page_size=3)
    pages_b = get_hash_str([1, 2, 99, 4, 5, 6], page_size=3)
    assert pages_a[0] != pages_b[0]  # page 0 differs (different tokens)
    assert pages_a[1] != pages_b[1]  # page 1 differs (different chain parent)


# --- node-tree helpers (compute_node_hash_values / split_node_hash_value) ---


class _StubNode:
    """Minimal stub matching the interface compute_node_hash_values reads."""

    def __init__(self, key, parent=None, hash_value=None):
        self.key = key
        self.parent = parent
        self.hash_value = hash_value


def test_compute_node_hash_values_uses_parent_last_hash():
    """compute_node_hash_values reads node.parent.hash_value[-1] as prior.

    Matches sglang.srt.mem_cache.utils.compute_node_hash_values.
    """
    parent = _StubNode(key=[10, 20], hash_value=[get_hash_str([10, 20])])
    node = _StubNode(key=[1, 2, 3], parent=parent)

    result = compute_node_hash_values(node, page_size=1)
    expected = get_hash_str([1, 2, 3], parent.hash_value[-1], page_size=1)
    assert result == expected


def test_split_node_hash_value_splits_at_page_boundary():
    """split_node_hash_value: first split_pages go to new node, rest stay.

    Matches sglang.srt.mem_cache.utils.split_node_hash_value.
    """
    child_hash_value = ["a", "b", "c", "d", "e"]
    new_node_hash, remaining = split_node_hash_value(
        child_hash_value, split_len=6, page_size=2
    )
    # split_pages = 6 // 2 = 3
    assert new_node_hash == ["a", "b", "c"]
    assert remaining == ["d", "e"]


def test_split_node_hash_value_none_input():
    """None input → (None, None)."""
    assert split_node_hash_value(None, split_len=4, page_size=2) == (None, None)
